version: '3'
services:
  guillotina:
    build: .
    command:
    - guillotina
    - -c
    - config-pg.yaml
    ports:
    - "8081:8081"
    - "50101:50101"
    volumes:
    - .:/usr/src/app
    - logvolume01:/var/log
    links:
    - postgres
    networks:
    - postgres
  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: secret
        POSTGRES_INITDB_ARGS: --data-checksums
        POSTGRES_DB: guillotina
    volumes:
    - postgres_data_cms:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  logvolume01: {}
  postgres_data_cms: {}

networks:
  postgres:
