{{- if .Values.front.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: volto-front
spec:
  type: {{ .Values.front.service.type }}
  ports:
  - name: front
    port: {{ .Values.front.service.externalPort }}
    targetPort: {{ .Values.front.service.internalPort }}
    protocol: {{ .Values.front.service.protocol }}
  selector:
    app: {{ template "name" . }}
    role: volto
{{- end -}}
